### ISSUE TITLE
Does this library follow a standard MsgPack based standard?

### ISSUE THREAD

**Issue by volfco** [choleraehyq/aiorpc#4]
Is there a standard being following here? 

I'm asking because I'm making some improvements for my own use, such as improved exception handling, which are changing some parts of the payload being sent back and forth. I'd love to merge them back in, but if there is a standard being followed I don't want to break it.

**Comment by choleraehyq** [comment]
Actually, I wrote this personal project just for learning asyncio, so feel free to send PR :-)

**Comment by volfco** [comment]
Awesome. There are a couple of things I've been tweaking and improving on that I'll make a PR for
